apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "order"
  description: "This website handles orders across all types."
spec:
  type: openapi
  lifecycle: production
  owner:  "guest"
  definition:
    $text: https://github.com/platform-dx/order-4c56331/blob/main/open-api.yaml
